### ISSUE TITLE
Need some examples with @type forward

### ISSUE THREAD

**Issue by bwnyasse** [fluent/fluent-plugin-grok-parser#21]
Is it possible t use it with source  @type forward and retrieve data with grok pattern in match filter ? 

i want to integrate it into a [log explorer for docker](https://github.com/bwnyasse/led)

**Comment by okkez** [comment]
Maybe you can do that with [fluent-plugin-parser](https://github.com/tagomoris/fluent-plugin-parser).
I don't have enough time to confirm this idea in this week.
Maybe fluent-plugin-parser works with v0.12.x.
Fluentd v0.14.x will merge https://github.com/fluent/fluentd/pull/1191

Maybe fluent.conf is like followings:

```
<source>
  @type forward
  # snip
  @label @PARSER
</source>

<label @PARSER>
  <filter>
    @type parser
    format grok
    <grok>
      pattern ...
    </grok>
  </filter>
</label>
(snip)
```
