### ISSUE TITLE
[Question] Add information about grok parser failures to log.

### ISSUE THREAD

**Issue by DanKans** [fluent/fluent-plugin-grok-parser#24]
Hi, 

Is it possible to add special field when grokparser failed (something similar that we have in logstash)?
I was thinking about something like this:

```fluentd
<filter type.stdout.web-log>
    @type parser
    reserve_data yes 
    key_name message
    hash_value_field grok
    <parse>
        @type grok
        <grok>
            pattern %{COMBINEDAPACHELOG}
        </grok>
        <grok>
            pattern %{GREEDYDATA:message}
            <record>
                grokfailure 'true'
            </record>
        </grok>
    </parse>
</filter>
```
In above scenario, I've added <record> section that will add specific field when second parser will be processed successfully. Unfortunately section <record> is not used in <grok>. 
Do you know any other methods how I can achieve this behaviour? 
Is it possible to add <record> section to grok plugin?

Thanks!

**Comment by okkez** [comment]
Does "grokparser failed" means no grok pattern matched?
NoneParser (default parser) parse record and `record["message"] = original message` when no grok pattern matched.

We cannot customize default parser, for now.
Is it enough to customize NoneParser's message_key?

**Comment by DanKans** [comment]
Hi @okkez,

I would like to add another indicator that will let me know and will be less space consuming and more searchable than adding whole message when all parsers before failed. 

If it is not possible to add field, maybe I will do something like this:

```
    <parse>
        @type grok
        <grok>
            pattern %{COMBINEDAPACHELOG1}
        </grok>
        <grok>
            pattern %{COMBINEDAPACHELOG2}
        </grok>
        <grok>
            pattern %{DATA:grokfailure} # This should create empty grokfailure field 
        </grok>
    </parse>
```

As result I got: 

```json
          "grok": {
            "grokfailure": ""
          },
```

Thanks!

**Comment by okkez** [comment]
If no grok pattern matched, we want to know unmatched message detail.

Could you describe logstash behavior or give me some pointers?
I'm not familiar with logstash.

```aconf
<source>
  @type dummy
  @label @dummy
  dummy [
    { "message1": "no grok pattern matched!", "prog": "foo" },
    { "message1": "/", "prog": "bar" }
  ]
  tag dummy.log
</source>

<label @dummy>
  <filter>
    @type parser
    key_name message1
    reserve_data true
    reserve_time true
    <parse>
      @type grok
      <grok>
        pattern %{PATH:path}
      </grok>
    </parse>
  </filter>
  <match dummy.log>
    @type stdout
  </match>
</label>
2016-11-25 16:37:49.026732769 +0900 dummy.log: {"message1":"no grok pattern matched!","prog":"foo","message":"no grok pattern matched!"}
2016-11-25 16:37:50.028024458 +0900 dummy.log: {"message1":"/","prog":"bar","path":"/"}
```

If you set `reserve_data false`, `record["message1"]` will not be shown.

**Comment by DanKans** [comment]
When grok parser has a failure, logstash is adding "_grokparserfailure" into tags field:

```json
    "tags": [
      "_grokparsefailure"
    ]
```

Then I can easily search for "tags: _grokparsefailure" to find out, with which logs, grok had problem.

I need to keep reserve_data in true state, because I have additional structure in logs from kubernetes API.

I think for my use case I can just add grokfailure field (last comment), and then search for it.

Thanks!

**Comment by okkez** [comment]
@DanKans I've added new parameter `grok_failure_key` and released new version.
Please try it.

**Comment by DanKans** [comment]
Hi @okkez 

Perfect! works as expected :) Only if all patterns are wrong `grok_failure_key` will be added.

Test case 1: 
```fluentd
    <parse>
        @type grok
        grok_failure_key grok_failure
        <grok>
            pattern !!WRONG PATTERN!!
        </grok>
    </parse>
```
Result:
```json
          "grok": {
            "message": "APACHE LOG,
            "grok_failure": "No grok pattern matched"
          },
```

Test case 2: 
```fluentd
    <parse>
        @type grok
        grok_failure_key grok_failure
        <grok>
            pattern !!WRONG PATTERN!!
        </grok>
        <grok>
            pattern %{GREEDYDATA:message}
        </grok>
    </parse>
```
Result:
```json
          "grok": {
            "message": "APACHE LOG,            
          },
```

Thank you!

**Comment by okkez** [comment]
Thank you for testing! :+1:
