### ISSUE TITLE
Time conversion always fail

### ISSUE THREAD

**Issue by ddzero2c** [fluent/fluent-plugin-grok-parser#30]
Hi, 

I try to parse the time of the following string but it alwasy fail
`May 23 11:50:40 localhost systemd[1]: Stopping System Logging Service...`

here is my config
```
<source>
  @type tail
  path /var/log/syslog
  tag test
  <parse>
    @type grok
    grok_pattern %{SYSLOGTIMESTAMP:timestamp:time:%d/%b/%Y:%H:%M:%S} %{GREEDYDATA:message}
  </parse>
</source>
```

and fail message
`2017-05-23 14:46:21.687243345 +0800 test: {"timestamp":null}`

If I just write the following pattern:
`%{SYSLOGTIMESTAMP:timestamp:time}`

the output is
`2017-05-23 15:08:57.449623167 +0800 test: {"timestamp":1495523337,"message":"localhost systemd[1]: Stopping System Logging Service..."}
`

Am I misunderstand something ?

**Comment by okkez** [comment]
Use `%{SYSLOGTIMESTAMP:timestamp}` instead.
We cannot specify time format in grok pattern immediately.

**Comment by ddzero2c** [comment]
So you mean the feature is still not ready yet ?

**Comment by okkez** [comment]
We don't have the feature to specify time format inline grok pattern.

See https://github.com/fluent/fluent-plugin-grok-parser#1-how-can-i-convert-types-of-the-matched-patterns-like-logstashs-grok

Or you can write your own grok pattern in custom pattern file.

See https://github.com/fluent/fluent-plugin-grok-parser#how-to-add-your-own-grok-pattern
https://github.com/fluent/fluent-plugin-grok-parser/blob/master/patterns/grok-patterns#L63-L78

**Comment by ddzero2c** [comment]
Oh I think I have understanding.

"For the time and array types, there is an optional 4th field after the type name. For the "time" type, you can specify a time format like you would in time_format."

So the 4th field just for parsing not formatting. Thanks!
