### ISSUE TITLE
TIMESTAMP_ISO8601 not working

### ISSUE THREAD

**Issue by JaisalSingh** [fluent/fluent-plugin-grok-parser#33]
My Source is 
`<source>
  @type tcp
  port 24224
  bind 0.0.0.0
  tag all
  format grok
  grok_pattern %{TIMESTAMP_ISO8601:time} +%{DATA:UNWANTED}: id=%{DATA:id} time="%{DATA:UNWANTED}" pri=%{BASE10NUM:pri:integer} fw=%{IP:fw} vpn=%{DATA:vpn} user=%{DATA:user} realm="%{DATA:realm}" roles="%{DATA:roles}" (type=%{WORD:type} )?(((proto=(%{DATA:proto})? src=(%{IP:src})? dst=%{IP:dst}? (dstname=%{DATA:dstname})?)?)?((( type=%{WORD:type})? op=(%{WORD:op})? arg="%{DATA:arg}?" result=%{WORD:result}?)? sent=(%{DATA:sent}) rcvd=(%{DATA:rcvd}) )?(agent="(%{DATA:agent})" duration=(%{DATA:duration}) )?)?msg="%{DATA:evt_id}: +%{DATA:msg}"$
</source>`

All the other fields are parsed but not the TIMESTAMP_ISO8601 one... and it also doesn't work when we use time as the name of the field... if I use tame as the name of the field then it is parsed into a string but the other fields which should be present are not. 

2016-05-06T13:10:54-07:00  UseLess: id=firewall time="2016-05-06 13:10:54" pri=6 fw=0.0.0.0 vpn=ive user=System realm="Admin Users" roles=".Administrators" type=mgmt msg="ERROR3012: Successfully executed 'Renew Credential Request (Admin)'.

**Comment by okkez** [comment]
You can use `%{TIMESTAMP_ISO8601:timestamp}` instead of `%{TIMESTAMP_ISO8601:time}`.

Because grok parser uses Fluentd built-in regexp parser internal.
regexp parser removes time_key if `keep_time_key` is `false`. `keep_time_key` is `false` by default.

**Comment by okkez** [comment]
no response.
