### ISSUE TITLE
Unknown format template 'grok'

### ISSUE THREAD

**Issue by johnr-spindance** [fluent/fluent-plugin-grok-parser#35]
When trying to use the v1.0.0 version of this plugin with fluentd 0.12.29, I am getting an error from fluentd saying that the grok template format is unknown? I am relatively new to fluentd and am not sure what this error is about.

`config error file="/etc/fluent/fluent.conf" error="Unknown format template 'grok'"`

Info on my setup...

I'm using fluentd in a docker container and I intend on using this grok parser to grab certain lines from /var/log/audit/audit.log...

Fluentd Version:
```
# fluentd --version
fluentd 0.12.29
```

Input Config:
```
      <source>
        @type tail
        path /var/log/audit/audit.log
        tag system.*
        format grok
        grok_pattern %{WORD:pam_module}\(%{DATA:pam_caller}\): session %{WORD:pam_session_state} for user %{USERNAME:username}(?: by %{GREEDYDATA:pam_by})?
      </source>
```

Error when I start fluentd:
```
2017-11-07 16:35:00 +0000 [error]: config error file="/etc/fluent/fluent.conf" error="Unknown format template 'grok'"
2017-11-07 16:35:00 +0000 [error]: fluentd main process died unexpectedly. restarting.
```

Steps to install fluentd-plugin-grok-parser plugin (from Dockerfile):
```
RUN \
  GEM='fluent-plugin-grok-parser' && \
  TAR_FILE='https://github.com/fluent/fluent-plugin-grok-parser/archive/v1.0.0.tar.gz' && \
  mkdir /${GEM} && \
  curl -sL "${TAR_FILE}" | \
    tar -xzvC /${GEM} --strip-components=1 && \
  cd /${GEM} && \
  gem build *.gemspec && \
  cd / && \
  fluent-gem install -N --conservative --minimal-deps \
    /${GEM}/*.gem && \
  cp -r /${GEM}/*.gem /etc/fluent/plugin && \
  rm -rf /${GEM}
```

**Comment by okkez** [comment]
You can install fluent-plugin-grok-parser 1.0.0 by following command:

```
$ fluent-gem install fluent-plugin-grok-parser -v 1.0.0
```

` error="Unknown format template 'grok'"` means that you could not install fluent-plugin-grok-parser properly.

Could you show me details about your docker image or Dockerfile?

**Comment by johnr-spindance** [comment]
This fixed my problem
