### ISSUE TITLE
More of a question than an issue

### ISSUE THREAD

**Issue by Matt-Dee** [fluent/fluent-plugin-grok-parser#44]
We just switched from filebeat/logstash.  With logstash we were able to tag different messages based on the grok that parsed them successfully.  Is it possible to tag messages differently based on the grok that successfully parsed?

something like...

```
<source>
  @type tail
  path /path/to/log
  tag grokked_log
  <parse>
    @type grok
    <grok>
      pattern %{COMBINEDAPACHELOG}
      time_format "%d/%b/%Y:%H:%M:%S %z"
      tag tag_one
    </grok>
    <grok>
      pattern %{IP:ip_address}
      tag tag_two
    </grok>
    <grok>
      pattern %{GREEDYDATA:message}
      tag tag_three
    </grok>
  </parse>
</source>
```

This would be an awesome feature if we could do this.  We are at the ground level of a project that we are about to open source.  It is a machine learning framework for the EFK stack.  Being able to tag individual log messages accordingly would be huge for us.

thanks in advance.

**Comment by mpohl56** [comment]
This would also be a nice feature for us too.

**Comment by okkez** [comment]
fluent-plugin-grok-parser is a parser plugin, it cannot edit tag because of the fluentd specification.
If you want to edit tag based on parsed records by grok, you can try [fluent-plugin-rewrite-tag-filter](https://github.com/fluent/fluent-plugin-rewrite-tag-filter/tree/v2.0.2#usage).
