### ISSUE TITLE
Requirements about docker/fluent/fluentd:v0.12.42

### ISSUE THREAD

**Issue by vanke-renzhe** [fluent/fluent-plugin-grok-parser#48]
Which version should i use？？？
Requirements chapter of readme : < 1.0.0  if fluentd >= v0.12.0
or “If you want to use this plugin with Fluentd v0.12.x or earlier, you can use this plugin version v1.0.0.”

**Comment by okkez** [comment]
If you use Fluentd v1, you should use this plugin v2.x.
If you use Fluentd v0.12.x, you must use this plugin v1.x.

I've updated requirements section.

**Comment by vanke-renzhe** [comment]
thanks!
