### ISSUE TITLE
Can i use grok in <match> or <filter>? fluent-plugin-grok-parser=v1.0.0

### ISSUE THREAD

**Issue by Renz2018** [fluent/fluent-plugin-grok-parser#49]
```
<match **>
@type copy

format grok
grok_pattern %{DATA:log_time} - %{DATA:log_name} - %{DATA:log_level} - %{GREEDYDATA:message}

<store>
@type stdout
</store>

<store>
@include common.elasticsearch.conf
</store>

</match>
```
I use grok parser like this but i did not get the result of grok parser

**Comment by okkez** [comment]
You can use fluent-plugin-grok-parser in `<source>` or `<filter>` with filter_parser plugin.
`<match>`'s format is for the formatter plugin.

See also:
* https://docs.fluentd.org/v0.12/articles/formatter-plugin-overview
* https://docs.fluentd.org/v0.12/articles/parser-plugin-overview
* https://docs.fluentd.org/v0.12/articles/filter_parser

**Comment by vanke-renzhe** [comment]
thanks，but if i have a lot of formats of logs and use same source input, should i write a log of grok_pattern in a filter section??

**Comment by okkez** [comment]
You can use multiple grok patterns.
See sample configurations in README.md.
