### ISSUE TITLE
help needed using multiline javastacktracepart pattern

### ISSUE THREAD

**Issue by hkailantzis** [fluent/fluent-plugin-grok-parser#69]
Hi there,

Could someone shed some light on how to parse multiline java stack traces using the javastacktracepart pattern (or any other pattern) in order to place the whole stacktrace in one field (to be able to view them in Kibana)?

Trying to use the following but doesn't seem to do the trick: 
```
<filter kubernetes.var.log.containers.app**>
      @type parser
      key_name log
        <parse>
          @type multiline_grok          
          <grok>
            pattern %{JAVASTACKTRACEPART:javastacktrace}
          </grok>
        </parse>
</filter>
```

but instead the javastacktrace field contain only one line of the stacktrace:

```
{
  "javastacktrace": "at java.io.foobar.javamethod(foobar.java:900)",
  "file": "foobar.java",
  "method": "javamethod",
  "line": "900",
  "class": "java.io.foobar"
}
```

**Comment by okkez** [comment]
Does it include full stacktrace in `log` field?
If yes, you cannot parse it using `JAVASTACKTRACEPART` pattern. Because the pattern `JAVASTACKTRACEPART` does not parse **full** stacktrace. It parses a part of Java stacktrace.
If no, you cannot parse it using multiline_grok parser plugin. Please use other plugin such as [fluent-plugin-concat](https://github.com/fluent-plugins-nursery/fluent-plugin-concat) or [fluent-plugin-detect-exceptions](https://github.com/GoogleCloudPlatform/fluent-plugin-detect-exceptions).

Could you show me your raw logs including Java stacktrace?

**Comment by hkailantzis** [comment]
hey @okkez , thanks for your prompt reply. Just need some help with the config bit. not sure what would be the right way. we also use in some cases the multiple grok patterns syntax: e.g. 

```
<filter kubernetes.var.log.containers.app**>
      @type parser
      key_name log
        <parse>
          @type multiline_grok          
          <grok>
            pattern %{another pattern here}
          </grok>
          <grok>
            pattern %{JAVASTACKTRACEPART:javastacktrace}
          </grok>
        </parse>
</filter>
```

Please find below a sample java log:

```
java.sql.SQLException: Network error IOException: Connection timed out: connect
   at net.sourceforge.jtds.jdbc.ConnectionJDBC2.<init>(ConnectionJDBC2.java:421)
   at net.sourceforge.jtds.jdbc.ConnectionJDBC3.<init>(ConnectionJDBC3.java:50)
   at net.sourceforge.jtds.jdbc.Driver.connect(Driver.java:185)
```

**Comment by okkez** [comment]
I assume that you use k8s.

k8s write logs like as followings:

```
{ "log": "java.sql.SQLException: Network error IOException: Connection timed out: connect", ...}
{ "log": "   at net.sourceforge.jtds.jdbc.ConnectionJDBC2.<init>(ConnectionJDBC2.java:421)", ...}
{ "log": "   at net.sourceforge.jtds.jdbc.ConnectionJDBC3.<init>(ConnectionJDBC3.java:50)", ...}
{ "log": "   at net.sourceforge.jtds.jdbc.Driver.connect(Driver.java:185)", ...}
```

The following configuration will concatenate logs including Java stacktrace(not tested):

```
<source>
  @type tail
  # snip
  @label @CONCAT
</source>

<label @CONCAT>
  <filter>
    @type concat
    key log
    multiline_start_regexp /^java/
    continuous_line_regext /^\s/
  </filter>
  <match>
    @type relabel
    @label @OUT
  </match>
</label>

<label @OUT>
  <match>
    @type elasticsearch
    # ... snip
  </match>
</label>
```

BTW, the bundled grok patterns don't include a pattern to parse multiline Java stacktrace.

**Comment by hkailantzis** [comment]
hey @okkez , thanks for the sample config. Eventually found a workaround with fluent-plugin-detect-exceptions... closing this issue.

**Comment by Passpes** [comment]
Hi @hkailantzis,
what is the workaround you found with fluent-plugin-detect-exceptions as I'm facing the same issue..

**Comment by hkailantzis** [comment]
HI @Passpes, just use this: https://github.com/GoogleCloudPlatform/fluent-plugin-detect-exceptions
