### ISSUE TITLE
Using array type with space delimiter

### ISSUE THREAD

**Issue by andersosthus** [fluent/fluent-plugin-grok-parser#71]
Hi,

I have a log item that has an array using space as delimiter, and I'm unable to get this to work with the array type.

Is this supported in any way? I've tried %{GREEDYDATA:myfield:array: } and then it splits each character up in separate items in the array, so I end up with a char array.

Example data: `values="[my/first/item my/second/item]"`
I would like an array like so: `["my/first/item", "my/second/item"]`

**Comment by okkez** [comment]
You cannot use a space as a delimiter with grok parser's array type.
You can use built-in parser_csv with grok parser if you want to use a space as a delimiter.

```
<source>
  @type dummy
  tag dummy
  dummy [
    { "message": "values=\"[my/first/item my/second/item]\"" }
  ]
</source>

<filter dummy>
  @type parser
  key_name message
  <parse>
    @type grok
    <grok>
      name parsed_values
      pattern values=\"\[%{GREEDYDATA:values}\]\"
    </grok>
  </parse>
</filter>

<filter dummy>
  @type parser
  key_name values
  <parse>
    @type csv
    delimiter " "
    keys key1,key2
  </parse>
</filter>

<match dummy>
  @type stdout
</match>
```

**Comment by andersosthus** [comment]
Hi,

Ok. That workaround works for me, thanks.
