### ISSUE TITLE
Two log structures output to two es indexes

### ISSUE THREAD

**Issue by ChenZheOnePiece** [fluent/fluent-plugin-grok-parser#81]
I have two logs  structures, if I want  save to es two index. Is it necessary to configure two source

**Comment by SmittyCooger** [comment]
if you mean how to separate the logs coming from one source, you can rewrite the tag of each log structure by the `rewrite_tag_filter` plugin then reroute them using the `route` plugin.
you can find more examples for routing events here :
https://docs.fluentd.org/configuration/routing-examples

**Comment by cosmo0920** [comment]
In Fluentd v1 world, using label instead of tag is better.https://github.com/tagomoris/fluent-plugin-route#example-2-use-label

**Comment by cosmo0920** [comment]
@skYl1r did answer for this issue.
If there is more question about this issue, please feel free to add comments.
Thank you for using this plugin!
